# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  creditcardmanager:
    image: creditcardmanager
    build:
      context: .
      dockerfile: CreditCardManager.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5177:5177
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
